services:

  product_db:
    image: postgres
    container_name: product_db
    ports:
      - 5433:5432
    volumes: 
      - product_db_data:/var/lib/postgresql/data
    env_file:
      - ./product-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_db:
    image: postgres
    container_name: user_db
    ports:
      - 5434:5432
    volumes: 
      - user_db_data:/var/lib/postgresql/data
    env_file:
      - ./user-service/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_kafka:
    image: apache/kafka
    container_name: user_kafka
    ports:
      - 9092:9092

  cart_redis:
    image: redis
    container_name: cart_redis
    ports:
      - 6379:6379
    volumes:
      - cart_redis_db:/data
    env_file:
      - ./cart-service/.env


volumes:
  product_db_data:
  user_db_data:
  cart_redis_db: