// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: availablility.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailablilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityRequest) Reset() {
	*x = AvailablilityRequest{}
	mi := &file_availablility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityRequest) ProtoMessage() {}

func (x *AvailablilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_availablility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityRequest.ProtoReflect.Descriptor instead.
func (*AvailablilityRequest) Descriptor() ([]byte, []int) {
	return file_availablility_proto_rawDescGZIP(), []int{0}
}

func (x *AvailablilityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AvailablilityRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AvailablilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availablility bool                   `protobuf:"varint,1,opt,name=availablility,proto3" json:"availablility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailablilityResponse) Reset() {
	*x = AvailablilityResponse{}
	mi := &file_availablility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailablilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailablilityResponse) ProtoMessage() {}

func (x *AvailablilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_availablility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailablilityResponse.ProtoReflect.Descriptor instead.
func (*AvailablilityResponse) Descriptor() ([]byte, []int) {
	return file_availablility_proto_rawDescGZIP(), []int{1}
}

func (x *AvailablilityResponse) GetAvailablility() bool {
	if x != nil {
		return x.Availablility
	}
	return false
}

var File_availablility_proto protoreflect.FileDescriptor

const file_availablility_proto_rawDesc = "" +
	"\n" +
	"\x13availablility.proto\x12\x05proto\"K\n" +
	"\x14availablilityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"=\n" +
	"\x15availablilityResponse\x12$\n" +
	"\ravailablility\x18\x01 \x01(\bR\ravailablility2b\n" +
	"\x14availablilityService\x12J\n" +
	"\visAvailable\x12\x1b.proto.availablilityRequest\x1a\x1c.proto.availablilityResponse\"\x00B1Z/github.com/Gergenus/commerce/cart-service/protob\x06proto3"

var (
	file_availablility_proto_rawDescOnce sync.Once
	file_availablility_proto_rawDescData []byte
)

func file_availablility_proto_rawDescGZIP() []byte {
	file_availablility_proto_rawDescOnce.Do(func() {
		file_availablility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_availablility_proto_rawDesc), len(file_availablility_proto_rawDesc)))
	})
	return file_availablility_proto_rawDescData
}

var file_availablility_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_availablility_proto_goTypes = []any{
	(*AvailablilityRequest)(nil),  // 0: proto.availablilityRequest
	(*AvailablilityResponse)(nil), // 1: proto.availablilityResponse
}
var file_availablility_proto_depIdxs = []int32{
	0, // 0: proto.availablilityService.isAvailable:input_type -> proto.availablilityRequest
	1, // 1: proto.availablilityService.isAvailable:output_type -> proto.availablilityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_availablility_proto_init() }
func file_availablility_proto_init() {
	if File_availablility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_availablility_proto_rawDesc), len(file_availablility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_availablility_proto_goTypes,
		DependencyIndexes: file_availablility_proto_depIdxs,
		MessageInfos:      file_availablility_proto_msgTypes,
	}.Build()
	File_availablility_proto = out.File
	file_availablility_proto_goTypes = nil
	file_availablility_proto_depIdxs = nil
}
